import { useRouter } from "next/router";
import Head from "next/dist/shared/lib/head";
import Navbar from "./Navbar";
import BackgroundImage from "./BackgroundImage";
import { navLinks } from "../constasnts";
import bg from "../public/assets/bg.png";

export function MainLayout({ children }) {
  const router = useRouter();

  const FindTitle = (navLinks) =>
    navLinks.find(
      (link) => (link.id === "/" ? "/" : `/${link.id}`) === router.asPath
    );
  const title = FindTitle(navLinks).title;

  return (
    <>
      <Head>
        <title>{title} | Ночные экскурсии Архыз</title>
        <meta name="keywords" content="Архыз,Ночные экскурсии,звёзды" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Navbar />
      <BackgroundImage src={bg} alt="background" />
      <div className="mt-16">{children}</div>
    </>
  );
}
