import { useRouter } from "next/router";
import Head from "next/dist/shared/lib/head";
import Navbar from "./Navbar";
import { navLinks } from "../constasnts";

export function MainLayout({ children }) {
  const router = useRouter();

  const FindTitle = (navLinks) =>
    navLinks.find(
      (link) => (link.id === "/" ? "/" : `/${link.id}`) === router.asPath
    );

  return (
    <>
      <Head>
        <title>{FindTitle(navLinks).title} | Ночные экскурсии Архыз</title>
        <meta name="keywords" content="Архыз,Ночные экскурсии,звёзды" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <footer></footer>
    </>
  );
}
