import { MainLayout } from "../components/MainLayout";
import Head from "next/dist/shared/lib/head";

export default function Reviews() {
  return (
    <MainLayout>
      <Head>
        <title>Ночные экскурсии Архыз</title>
        <meta name="keywords" content="Архыз,Ночные экскурсии,звёзды" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <h1>Отзывы</h1>
    </MainLayout>
  );
}
